version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:
  vue:
    build: ./
    command: bash -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./example/:/app/
    logging: *default-logging
    ports:
      - 8080:8080
