version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:

  ruby:
    build: ./
    command: bash -c "/app/boot.sh"
    working_dir: /app
    volumes:
       - ./:/app/
    logging: *default-logging
    ports:
      - 3000:3000
