version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:

  python:
    build: ./
    volumes:
      - ./src/:/app/
    working_dir: /app/
    logging: *default-logging
    command: python hello.py
    links:
      - redis

  redis:
    image: redis:6.0-rc1
    logging: *default-logging
