version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:
  node:
    build: ./
    command: >
      bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./example/:/app/
    logging: *default-logging
    ports:
      - 3000:3000
