version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:

  flask:
    build: ./
    environment:
      - FLASK_DEBUG=0
      - FLASK_ENV="development"
    volumes:
      - ./src/:/app/
    working_dir: /app
    command: flask run -p 80 -h 0.0.0.0
    logging: *default-logging
    ports:
      - 80:80
