version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:

  scala:
    build: ./
    volumes:
      - ./example/:/app/
    working_dir: /app/
    command: activator 'run -Dconfig.file=conf/application-dev.conf -Dconfig.log=DEBUG 9000'
    tty: true
    ports:
      - 9000:9000
    logging: *default-logging
