version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:

  scala:
    build: ./
    volumes:
      - ./src/:/app/
    working_dir: /app/
    command: bash -c 'activator "run -Dconfig.file=conf/application.conf -Dconfig.log=DEBUG 9000"'
    ports:
      - 9000:9000
    logging: *default-logging
