version: "3.4"

services:
  dotnet:
    image: mcr.microsoft.com/dotnet/core/sdk:2.1
    volumes:
      - ./example/samples/helloworld/:/src/
    working_dir: /src/
    command: >
      bash -c "dotnet restore && dotnet run"
    ports:
      - 5000:5000
      - 5001:5001

  shell:
    image: mono:6.6
    working_dir: /app/
    tty: true
