version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:

  proxy:
   image: nginx:stable-alpine
   volumes:
    - ./public_html/:/var/www/site/
    - ./ssl/:/etc/ssl/
    - ./proxy.conf:/etc/nginx/conf.d/default.conf
   logging: *default-logging
   ports:
    - 443:443
   extra_hosts:
    - "local.example.com:127.0.0.1"
    #if you wish to use
    #grep "127.0.0.1 local.example.com" /etc/hosts || echo "127.0.0.1 local.example.com" >> /etc/hosts
