version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50M"
    max-file: "5"

services:

  cron:
    build: ./
    volumes:
      - ./:/app/
    command: bash -c "sh /app/cron-env.sh &&
                      cron && tail -f /var/log/cron.log"
    logging: *default-logging
